version: '3'
services:
    HEAD:
        image: hanson:latest
        container_name: "HEAD"
        environment:
            - DISPLAY=:1
            - QT_X11_NO_MITSHM=1
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /home/tesfa/.tmux.conf:/home/hanson_dev/.tmux.conf
            - /home/tesfa/.ssh/:/root/.ssh/
            - /home/tesfa/.ssh/:/home/hansondev/.ssh
            - /home/tesfa/clone_dir/sophia_blender_lfs:/home/hansondev/hansonrobotics/HEAD/src/sophia_blender_lfs
            - /home/tesfa/clone_dir/hr_launchpad:/home/hansondev/hansonrobotics/hr_launchpad
        ports:
            - 8000:8000
            - 8004:6006
            - 4000:4000
            - 4242:4242
            - 11311:11311
            - 9094:9094
            - 9090:9090
        privileged: true
        user: root
        links:
            - mongodb
        depends_on:
            - mongodb
        command: python /home/hansondev/hansonrobotics/hr_launchpad/misc.py
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
